version: '3.7'
services:
  mongodb_container:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  feed_service:
    platform: linux/x86_64
    build:
      context: ./feedservice
      dockerfile: Dockerfile
    environment:
      MONGODB_USERNAME: feed-user
      MONGODB_PASSWORD: ${MONGODB_FEED_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - mongodb_container
    links:
      - mongodb_container
    restart: on-failure

volumes:
  mongodb_data_container:
