version: '3.7'
services:
  mongodb_container:
    container_name: mongodb
    image: mongo:latest
    env_file:
      - ./config/dev.env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  feed_service:
    platform: linux/x86_64
    build:
      context: ./feedservice
      dockerfile: Dockerfile
    env_file:
      - ./config/dev.env
    ports:
      - 8080:8080
    depends_on:
      - mongodb_container
    links:
      - mongodb_container
    restart: on-failure

volumes:
  mongodb_data_container:
